I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 190, in script
    python:
  File "renpy/common/00start.rpy", line 191, in <module>
    renpy.execute_default_statement(True)
  File "game/script.rpy", line 25, in set_default
    default learned = false
  File "game/script.rpy", line 25, in <module>
    default learned = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 190, in script
    python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 191, in <module>
    renpy.execute_default_statement(True)
  File "renpy/exports.py", line 3590, in execute_default_statement
    i.set_default(start)
  File "game/script.rpy", line 25, in set_default
    default learned = false
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 25, in <module>
    default learned = false
NameError: name 'false' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
12_prototype 1.0
Wed May 26 12:22:37 2021
